name: Build Windows wheel

on:
  workflow_dispatch:          # run manually
  push:
    branches: [ master ]      # re-build when you push

jobs:
  build-wheel:
    runs-on: windows-latest
    strategy:
      matrix:
        pyver: ["3.11", "3.12", "3.13"]  # build wheels you actually need

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.pyver }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.pyver }}

    - name: Install build deps
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install build ninja lz4 gymnasium pybind11

    - name: Build wheel
      run: python -m build --wheel --outdir dist

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v4
      with:
        name: nes-py-wheels
        path: dist/*.whl
